version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'vost'
      MYSQL_ROOT_PASSWORD: 'SuperRootPassword@@'
    expose:
    - 3306
    network_mode: "bridge"

  http:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
    - "db"
    expose:
    - 80/tcp
    volumes:
    - .:/app
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:vost.mariosantos.net"
    - "traefik.port=80"
    - "traefik.frontend.entryPoints=http,https"
    network_mode: "bridge"
