version: '3.1'

services:
  app:
    build: .
    working_dir: /var/www
    depends_on:
    - database
    networks:
    - web
    volumes:
    - ./:/var/www
  nginx:
    image: nginx
    networks:
    - web
    labels:
    - 'traefik.enable=true'
    - 'traefik.frontend.rule=Host:vost.mariosantos.net,ocorrencias.vost.pt'
    - 'traefik.port=80'
    - 'traefik.docker.network=web'
    volumes:
    - ./:/var/www
    - ./.docker/nginx.conf:/etc/nginx/nginx.conf
  database:
    image: mariadb
    networks:
    - web
    environment:
    - MYSQL_ROOT_PASSWORD=SuperRootPassword
    - MYSQL_DATABASE=vost
networks:
  web:
    external: true