version: '3.1'

services:
  app:
    build: .
    working_dir: /opt/www
    ports:
    - '9000:9000'
    networks:
    - vost
    volumes:
    - ./:/opt/www
  nginx:
    image: nginx
    networks:
    - vost
    ports:
    - "8087:80"
    volumes:
    - ./:/opt/www
    - ./.docker/nginx.conf:/etc/nginx/nginx.conf
  database:
    image: mariadb
    networks:
    - vost
    environment:
    - MYSQL_ROOT_PASSWORD=SuperRootPassword
    - MYSQL_DATABASE=vost
networks:
  vost:
    external: true