version: '2'
services:
  web:
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
    - ./.docker/site.conf:/etc/nginx/conf.d/default.conf
    networks:
    - code-network
  php:
    build:
      context: .docker
    volumes:
    - .:/var/www
    networks:
    - code-network
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '@SuperRootPassword@'
      MYSQL_DATABASE: 'vost'
    networks:
    - code-network

networks:
  code-network:
    driver: bridge
